name: Morning Twilio Calls (5 times)

on:
  schedule:
    - cron: '30 5 * * *'   # 11:00 AM IST
    - cron: '32 5 * * *'   # 11:02 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST
    - cron: '0 7 * * *'    # 12:30 PM IST
    - cron: '30 9 * * *'   # 03:00 PM IST
  workflow_dispatch:     # manual trigger for testing

jobs:
  make-call:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Make one Twilio call
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          CALL_FROM: ${{ secrets.CALL_FROM }}
          CALL_TO: ${{ secrets.CALL_TO }}
          TWIML_URL: ${{ secrets.TWIML_URL }}
        run: node call_single.js
